language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3
jobs:
  include:
    - name: flake8
      python: 3.8
      install: pip install tox
      script: tox -e flake8
      after_success:
    # coveralls.io never reports commit statuses for some reason, and of course
    # you don't get support for a free product
    - name: coverage
      python: 3.8
      install: pip install tox
      script:
        - tox -e coverage
        - coveage report -m --fail-under=100
      after_success:
install:
  - pip install coverage coveralls -cconstraints.txt
  - pip install freezegun flake8
  - pip install --no-deps -e .
script:
  - coverage run -m gtimelog.tests
after_success:
  - coveralls
notifications:
  email: false
